#ifndef CUSTOM_SHIMS_H
#define CUSTOM_SHIMS_H

#define unbundledmodule0_wasi_snapshot_preview1__adapter_close_badfd wasisnapshotpreview1_adapter_close_badfd
#define unbundledmodule0_wasi_snapshot_preview1__clock_time_get wasisnapshotpreview1_clock_time_get
#define unbundledmodule0_wasi_snapshot_preview1__environ_get wasisnapshotpreview1_environ_get
#define unbundledmodule0_wasi_snapshot_preview1__environ_sizes_get wasisnapshotpreview1_environ_sizes_get
#define unbundledmodule0_wasi_snapshot_preview1__fd_advise wasisnapshotpreview1_fd_advise
#define unbundledmodule0_wasi_snapshot_preview1__fd_close wasisnapshotpreview1_fd_close
#define unbundledmodule0_wasi_snapshot_preview1__fd_fdstat_get wasisnapshotpreview1_fd_fdstat_get
#define unbundledmodule0_wasi_snapshot_preview1__fd_filestat_get wasisnapshotpreview1_fd_filestat_get
#define unbundledmodule0_wasi_snapshot_preview1__fd_pread wasisnapshotpreview1_fd_pread
#define unbundledmodule0_wasi_snapshot_preview1__fd_prestat_dir_name wasisnapshotpreview1_fd_prestat_dir_name
#define unbundledmodule0_wasi_snapshot_preview1__fd_prestat_get wasisnapshotpreview1_fd_prestat_get
#define unbundledmodule0_wasi_snapshot_preview1__fd_read wasisnapshotpreview1_fd_read
#define unbundledmodule0_wasi_snapshot_preview1__fd_readdir wasisnapshotpreview1_fd_readdir
#define unbundledmodule0_wasi_snapshot_preview1__fd_seek wasisnapshotpreview1_fd_seek
#define unbundledmodule0_wasi_snapshot_preview1__fd_write wasisnapshotpreview1_fd_write
#define unbundledmodule0_wasi_snapshot_preview1__path_filestat_get wasisnapshotpreview1_path_filestat_get
#define unbundledmodule0_wasi_snapshot_preview1__path_open wasisnapshotpreview1_path_open
#define unbundledmodule0_wasi_snapshot_preview1__path_readlink wasisnapshotpreview1_path_readlink
#define unbundledmodule0_wasi_snapshot_preview1__path_unlink_file wasisnapshotpreview1_path_unlink_file
#define unbundledmodule0_wasi_snapshot_preview1__poll_oneoff wasisnapshotpreview1_poll_oneoff
#define unbundledmodule0_wasi_snapshot_preview1__proc_exit wasisnapshotpreview1_proc_exit
#define unbundledmodule0_wasi_snapshot_preview1__random_get wasisnapshotpreview1_random_get
#define unbundledmodule0_wasi_snapshot_preview1__sched_yield wasisnapshotpreview1_sched_yield

#endif
